import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `supabase start`/`supabase db reset` (gitignored local
    // CLI runtime state, e.g. the bundled Edge Runtime script) — not
    // source, never authored, and not reviewable/fixable code.
    "supabase/.temp/**",
  ]),
  {
    // Playwright fixtures take a `use` callback parameter — react-hooks'
    // rules-of-hooks otherwise misreads it as a React Hook call because of
    // the name alone. This directory has no React components in it.
    files: ["tests/e2e/**/*.ts"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
    },
  },
]);

export default eslintConfig;
